/:
  controller: Main
  action: home

/a-propos:
  controller: Main
  action: aboutUs

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/install:
  controller: Install
  action: install

/prebuild:
  controller: PageBuilder
  action: createpage

/build:
  controller: PageBuilder
  action: SetComponent
  
/forgot-pwd:
  controller: PwdRecovery
  action: forgotPwd

/resetpwd:
  controller: PwdRecovery
  action: resetPwd

/pagebuilder:
  controller: PageBuilder
  action: renderPages

/update-user:
  controller: UserUpdate
  action: updateUser

/connection-error:
  controller: Error
  action: notConnected

/uploadimg:
  controller: ImgUploader
  action: uploader