/:
  controller: Main
  action: home

/aboutus:
  controller: Main
  action: aboutUs

/reviews/add:
  controller: ReviewController
  action: showAddReviewForm

/review:
  controller: ReviewController
  action: showApprovedReview

/contact:
  controller: Main
  action: contact

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/install:
  controller: Install
  action: install

/prebuild:
  controller: PageBuilder
  action: createpage

/build:
  controller: PageBuilder
  action: SetComponent
