/:
  controller: Main
  action: home

/aboutus:
  controller: Main
  action: aboutUs

/addreview:
  controller: ReviewController
  action: createReview

/review:
  controller: ReviewController
  action: showApprovedReview

/unreview:
  controller: ReviewController
  action: manageReview

/myreview:
  controller: ReviewController
  action: updateReview


/contact:
  controller: Main
  action: contact

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/install:
  controller: Install
  action: install

/prebuild:
  controller: PageBuilder
  action: createpage

/build:
  controller: PageBuilder
  
/forgot-pwd:
  controller: PwdRecovery
  action: forgotPwd

/resetpwd:
  controller: PwdRecovery
  action: resetPwd

/pagebuilder:
  controller: PageBuilder
  action: renderPages

/previewpage:
  controller: PageBuilder
  action: preview

/showallpages:
  controller: PageBuilder
  action: showAllPages
  
/deletepage:
  controller: PageBuilder
  action: deletePage

/updatepage:
  controller: PageBuilder
  action: updatePage

/update-user:
  controller: UserUpdate
  action: updateUser

/connection-error:
  controller: Error
  action: notConnected

/uploadimg:
  controller: ImgUploader
  action: uploader