/:
  controller: Main
  action: home

/a-propos:
  controller: Main
  action: aboutUs

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/install:
  controller: Install
  action: install

/prebuild:
  controller: PageBuilder
  action: createpage

/build:
  controller: PageBuilder
  action: SetComponent

/page:
  controller: ViewPage
  action: show